"""
Grooming Workflow
================

INVEST User Story Scoring — evaluates a Jira user story against 10 GDS-aligned criteria,
rewrites the story to achieve a perfect score, and posts the full assessment as a
Jira comment so the BA can update the ticket accordingly.
"""

from agno.workflow import Step, Workflow

from agents.architect import architect
from agents.judge import judge

# ---------------------------------------------------------------------------
# Create Workflow
# ---------------------------------------------------------------------------
grooming = Workflow(
    id="grooming",
    name="User Story Quality Scorer",
    description="INVEST scoring: fetch Jira ticket → score 10 criteria with RAG status → rewrite story → post assessment comment for BA review",
    steps=[
        Step(
            name="Score User Story",
            agent=architect,
            description="""You are the User Story Scoring Analyst. Score the Jira user story against the 10 INVEST criteria.

Input: A Jira ticket ID (e.g., GDS-5) provided in the workflow input.

Step 1 — Fetch:
Use the fetch_jira_ticket tool to retrieve the full ticket (summary, description, acceptance criteria, priority).

Step 2 — Initial Evaluation:
Score the original story 1–10 per criterion and assign RAG status:
  🔴 Red   (1–4): Not met
  🟡 Amber (5–7): Partially met
  🟢 Green (8–10): Fully met

Criteria to evaluate:
  1. Independent      — No dependency on other stories to be delivered
  2. Negotiable       — Scope is open for team discussion on how to implement
  3. Valuable         — Clear measurable value to the end user
  4. Estimable        — Team can confidently size this story
  5. Small            — Fits within a single sprint
  6. Testable         — Acceptance criteria specific enough for automation
  7. Clear & Concise  — Plain language, no ambiguity
  8. Prioritised      — Business priority and user impact clearly stated
  9. Acceptance Criteria — Complete, unambiguous, verifiable ACs
  10. User-Centric    — "As a [user] / I want [goal] / So that [benefit]" format

Step 3 — Enhancement Recommendations:
For every Red or Amber criterion, state the specific gap and provide exact wording/phrasing to fix it.

Step 4 — Rewrite:
Produce the enhanced user story incorporating all recommendations. Target 10/10 on every criterion.
Include rewritten summary, description, and numbered acceptance criteria.

Step 5 — Re-score:
Score the enhanced story on all 10 criteria to confirm improvements.

Output a GroomingAssessment JSON with these fields:
  - ticket_id: the Jira ticket ID
  - original_story: full original story text
  - criteria_scores: list of 10 CriterionScore (criterion, score, rag, finding, recommendation)
  - initial_total: sum of initial scores
  - enhanced_story: full rewritten story text
  - enhanced_criteria_scores: list of 10 CriterionScore for enhanced story
  - final_total: sum of final scores
  - overall_recommendation: "approve" (≥80) / "refine" (50–79) / "reject" (<50) based on initial_total
  - summary: 2–3 sentence executive summary of key gaps for the BA
  - timestamp: current ISO 8601 timestamp""",
        ),
        Step(
            name="Post Assessment to Jira",
            agent=architect,
            description="""Post the INVEST scoring assessment as a Jira comment so the BA can update the ticket.

Input: The GroomingAssessment from the previous step.

Use the add_jira_comment tool to post to the ticket. Format the comment EXACTLY as follows:

---
## 📊 User Story Quality Assessment

**Ticket**: {ticket_id}
**Analyst**: Quality Autopilot — User Story Scoring Analyst
**Date**: {timestamp}

---
### Original Story Score: {initial_total}/100 → {APPROVE / REFINE / REJECT}

| # | Criterion | Score | RAG | Finding |
|---|-----------|-------|-----|---------|
| 1 | Independent | {score}/10 | {🔴/🟡/🟢} | {finding} |
| 2 | Negotiable | ... | ... | ... |
| 3 | Valuable | ... | ... | ... |
| 4 | Estimable | ... | ... | ... |
| 5 | Small | ... | ... | ... |
| 6 | Testable | ... | ... | ... |
| 7 | Clear & Concise | ... | ... | ... |
| 8 | Prioritised | ... | ... | ... |
| 9 | Acceptance Criteria | ... | ... | ... |
| 10 | User-Centric | ... | ... | ... |

---
### 🔧 Enhancement Recommendations
- **[Criterion]**: {specific_recommendation}
(one bullet per Red/Amber criterion only)

---
### ✅ Enhanced User Story (Targeting 10/10)

{enhanced_story}

---
### Enhanced Story Score: {final_total}/100

| # | Criterion | Score | RAG |
|---|-----------|-------|-----|
(re-scored table for enhanced story)

---
### 📝 BA Action Required
{summary — 2–3 sentences telling the BA exactly what to update in the ticket}

*Generated by Quality Autopilot | User Story Scoring Analyst*

---

After posting, confirm with the ticket URL and the overall recommendation.""",
        ),
    ],
)
